apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejsdocker-deployment
spec:
  selector:
    matchLabels:
      app: nodejsdocker
  replicas: 1
  template:
    metadata:
      labels:
        app: nodejsdocker
    spec:
      containers:
      - name: nodejsdocker
    # enter the path to your image, be sure to include the correct region prefix    
        image: vidyutv/nodejsdocker:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nodejsdocker-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nodejsdocker
