apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodedocker-deployment
spec:
  selector:
    matchLabels:
      app: nodedocker
  replicas: 1
  template:
    metadata:
      labels:
        app: nodedocker
    spec:
      containers:
      - name: nodedocker
    # enter the path to your image, be sure to include the correct region prefix    
        image: tarunghai/nodeapp:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nodedocker-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nodedocker
